name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
          target: [x64, x86]
          python_version: [3,7, 3.8, 3,9, "3.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      # - run: cargo build --all-features
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Build wheels
        # uses: PyO3/maturin-action@v1
        # with:
        #   target: ${{ matrix.platform.target }}
        #   args: --release --all-features --out dist --find-interpreter
        #   sccache: 'true'
        #   manylinux: auto
        run: |
          python -m pip install --upgrade pip
          python -m venv .env
          source .env/bin/activate
          pip install maturin
          maturin build --release --out dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.target }}
          path: dist
